name: Deploy to S3

on:
  push:
    branches:
      - inayat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Ensure this matches your AWS region

      # Step 3: Sync files to S3
      - name: Upload Files to S3 Bucket
        run: |
          aws s3 sync ./out/ s3://portfolio-inayat --delete \
            --cache-control "max-age=31536000,public" \
            --exclude "*.html"
